- core/models/base/CommunityModelBase.php
This is needed for the [autoregister plugin](https://github.com/midasplatform/autoregister/blob/master/Notification.php#L38).
> Issue callback upon community creation

- core/layouts/layout.phtml
> Adding a unique class for upload button.

- modules/tracker/controllers/components/ApiComponent.php
- modules/tracker/models/base/TrendModelBase.php
- modules/tracker/models/pdo/TrendModel.php
- modules/tracker/tests/controllers/ApiControllerTest.php
Multiple related PRs to add units to the tracker module's scalarAdd API method.
https://github.com/midasplatform/Midas/pull/118
https://github.com/midasplatform/pydas/pull/26
> [WIP] Add units to tracker module scalarAdd API

- .styleci.yml
- core/controllers/ShareController.php
- core/models/pdo/MetadataModel.php
- modules/api/tests/controllers/CallItemMethodsTest.php
- modules/tracker/views/scalar/details.phtml
A stray scalar that I neglected to format earlier.
> Format Scalar details Value to 4 decimals

- core/controllers/AdminController.php
- core/controllers/components/UpgradeComponent.php
- core/views/admin/upgrade.phtml
- tests/DatabaseSetup.php
There are about three ways to find a module version and apparently I did not notice this was using the wrong one. Future work is to obliterate those other ways. :boom:
> Fix upgrade tab

- library/Midas/Mail.php
- library/Midas/Service/AppEngine/Mail.php
- library/Midas/Service/SendGrid/Mail.php
- modules/mail/Notification.php
> Fix broken App Engine mail and corrupt message body in SendMail

- core/public/js/common/common.browser.js
Fixes #139. PTAL @cpatrick @mgrauer.
> Fix checked resource submenu

- modules/tracker/models/base/SubmissionModelBase.php
- modules/tracker/models/pdo/SubmissionModel.php
> Add a mechanism to get the scalars of only key metrics.

- core/controllers/CommunityController.php
- core/public/js/community/community.manage.js
- core/public/js/community/community.selectgroup.js
- core/public/js/community/community.view.js
- core/views/community/manage.phtml
- core/views/community/selectgroup.phtml
- core/views/community/view.phtml
> Directly add a user to a community/group

- modules/api/library/APIEnabledNotification.php
> Fix legacy API help page

- modules/tracker/public/js/trend/trend.view.js
There are a few errors I'm tracking down.  The first commit fixes the error from resetting the axes zoom.
> [WIP] Tracker plot checks for zoom before resetting

- modules/thumbnailcreator/controllers/components/ImagemagickComponent.php
The module should really just be rewritten from scratch.
@cpatrick @mgrauer PTAL.
> Fix thumbnailer (again)

- modules/tracker/Notification.php
Ready for review.
The gmail notifications weren't showing up correctly.  I also reduced the verbosity of the subject line.
> Correct gmail action from tracker notification

- core/configs/database.ini
Fixes an issue incidental to #182, which otherwise I cannot reproduce at present.
PTAL @cpatrick @mgrauer.
> Do not set values in database.ini that are likely to be real

- docs/installation/linux.md
> Specify Directory AllowOverride in docs

- composer.json
- core/controllers/AdminController.php
- core/controllers/InstallController.php
- core/models/pdo/ActivedownloadModel.php
> Allow unsecure http composer downloads

- modules/tracker/models/pdo/AggregateMetricModel.php
- modules/tracker/tests/databaseDataset/aggregateMetric.xml
- modules/tracker/tests/models/base/AggregateMetricModelTest.php
@cpatrick PTAL.
This was failing when there was only 1 value in the list.
> Improve robustness of Tracker percentile calculation

- modules/tracker/controllers/components/ApiComponent.php
- modules/tracker/tests/controllers/ApiComponentTest.php
@cpatrick PTAL
This *is* the API call you've been looking for.
> Add tracker.aggregatemetrics.update json API and test

- modules/tracker/Notification.php
- modules/tracker/controllers/ProducerController.php
- modules/tracker/controllers/components/ApiComponent.php
- modules/tracker/models/base/AggregateMetricSpecModelBase.php
- modules/tracker/models/pdo/AggregateMetricSpecModel.php
- modules/tracker/public/js/producer/producer.aggregateMetric.js
- modules/tracker/public/js/producer/producer.list.js
- modules/tracker/public/js/producer/producer.view.js
- modules/tracker/views/producer/aggregatemetric.phtml
- modules/tracker/views/producer/list.phtml
- modules/tracker/views/producer/view.phtml
> Schedule notifications for aggregate metrics

- modules/tracker/Notification.php
> Add callback for tracker aggregate metric notification link

- modules/tracker/public/js/producer/producer.aggregateMetric.js
@cpatrick 
This should fix the issues we saw in testing.
> Specify json ams rest

- modules/tracker/models/pdo/AggregateMetricSpecModel.php
@cpatrick @jamiesnape PTAL.  This one is a creampuff.
:fish_cake:
> Set aggregate metric alerts to high priority

- core/tests/databaseDataset/default.xml
- modules/tracker/tests/controllers/CMakeLists.txt
- modules/tracker/tests/controllers/SubmissionControllerTest.php
- modules/tracker/tests/databaseDataset/aggregateMetric.xml
- modules/tracker/tests/databaseDataset/submission.xml
> Add test for submission controller

- modules/tracker/configs/module.ini
- modules/tracker/database/mysql/2.0.3.sql
- modules/tracker/database/upgrade/2.0.3.php
- modules/tracker/models/base/ProducerModelBase.php
Ready for review, fairly simple, only adds one column to tracker_producer
> Add histogram_max_x to tracker_producer

- README.md
> Prefer Girder to Midas in README

- composer.json
- tests/CMakeLists.txt
FWIW, this will turn CI back to green. PTAL @mgrauer.
> Fix SecurityCheck test

- core/controllers/FolderController.php
- core/controllers/ItemController.php
- core/controllers/UserController.php
See http://resources.infosecinstitute.com/http-verb-tempering-bypassing-web-authentication-and-authorization/
Co-authored-by: Matt McCormick <matt.mccormick@kitware.com>
Co-authored-by: Michael Grauer <michael.grauer@kitware.com>
> BUG: Update viewAction to accept only valid verbs
